name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          brew uninstall go
          mkdir -p $(brew --repo)/Library/Taps/kadel
          ln -s $PWD $(brew --repo)/Library/Taps/kadel/homebrew-odo
          brew update-reset
          brew tap --repair
          brew audit kadel/odo/odo
          brew install -v kadel/odo/odo
          brew test kadel/odo/odo
